### ISSUE TITLE
There is a scrollbar when viewing the template studio app that does not need to exist

### ISSUE THREAD

**Issue by nithilan4** [accordproject/template-studio#128] opened 2019-10-26 15:41 UTC
My screen resolution is 1920x1080, and I see this when I visit the site.
![image](https://user-images.githubusercontent.com/43860191/67622149-ff52e800-f7dc-11e9-8287-f8cb5d8941d4.png)

It also messes with the "contribute on github" banner
![image](https://user-images.githubusercontent.com/43860191/67622166-227d9780-f7dd-11e9-82e9-566767d77a78.png)

**Comment by jeromesimeon** [comment] 2019-10-26 15:48
> My screen resolution is 1920x1080, and I see this when I visit the site.
> ![image](https://user-images.githubusercontent.com/43860191/67622149-ff52e800-f7dc-11e9-8287-f8cb5d8941d4.png)
> 
> It also messes with the "contribute on github" banner
> ![image](https://user-images.githubusercontent.com/43860191/67622166-227d9780-f7dd-11e9-82e9-566767d77a78.png)

Thanks for the bug report @nithilan4 

Could you please provide:
- OS info
- Browser info

**Comment by nithilan4** [comment] 2019-10-26 15:49
OS: Windows 10 Home
Browser: Chrome

**Comment by jeromesimeon** [comment] 2019-10-26 15:50
Also, from your screenshot, something seems to be going wrong with the fonts. Here is mine:

![Screenshot 2019-10-26 at 11 49 41 AM](https://user-images.githubusercontent.com/670099/67622275-c91a6600-f7e6-11e9-8c1d-0ba2af2ab069.png)

This might be a distinct issue.

**Comment by jeromesimeon** [comment] 2019-10-26 15:51
> Also, from your screenshot, something seems to be going wrong with the fonts. Here is mine (on MacOS Chrome 78):
> 
> ![Screenshot 2019-10-26 at 11 49 41 AM](https://user-images.githubusercontent.com/670099/67622275-c91a6600-f7e6-11e9-8c1d-0ba2af2ab069.png)
> 
> This might be a distinct issue.

**Comment by nithilan4** [comment] 2019-10-26 15:53
I tried on a chromebook, and got the same exact thing, along with scrollbar.

**Comment by jeromesimeon** [comment] 2019-10-26 15:54
Thanks! @irmerk would you mind reviewing @nithilan4's PR and see if the change would create issues on other browsers/platforms?

**Comment by nithilan4** [comment] 2019-10-26 15:55
To be honest there shouldn't really be any bottom padding there. My chromebook has even larger of a scrollbar.

**Comment by nithilan4** [comment] 2019-10-26 16:04
![image](https://user-images.githubusercontent.com/43860191/67622514-6c1bb180-f7e0-11e9-8304-9d4a9a05224a.png)
This is the source of the strange font issue.

**Comment by jeromesimeon** [comment] 2019-10-26 16:07
> ![image](https://user-images.githubusercontent.com/43860191/67622514-6c1bb180-f7e0-11e9-8304-9d4a9a05224a.png)
> This is the source of the strange font issue.

Would you be willing to work on a fix for that that could go into your PR? We can then review both. I'll have to find a Windows machine to try it out.

**Comment by nithilan4** [comment] 2019-10-26 16:22
sure!

**Comment by jeromesimeon** [comment] 2019-10-26 19:18
I could reproduce the issue with certain sizes on Windows: 
<img width="1305" alt="Screenshot 2019-10-26 at 3 16 19 PM" src="https://user-images.githubusercontent.com/670099/67624809-bd896800-f803-11e9-9496-7083e6f2d4a9.png">

It does look nicer with the proposed fixed in #127 
<img width="1301" alt="Screenshot 2019-10-26 at 3 16 32 PM" src="https://user-images.githubusercontent.com/670099/67624812-c7ab6680-f803-11e9-8442-8ac15f2af390.png">

**Comment by irmerk** [comment] 2019-10-26 21:01
I believe this is finished with #127

**Closed by irmerk** 2019-10-26 21:01 UTC
Labels: Difficulty: Medium, Hacktoberfest
